// Run: node scripts/seedFirestore.mjs
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, doc, setDoc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyBdCVlDKiWyuZyNFwTlWE6LiHAq2vA8WKU",
  authDomain: "autonova-salon.firebaseapp.com",
  projectId: "autonova-salon",
  storageBucket: "autonova-salon.firebasestorage.app",
  messagingSenderId: "166105733449",
  appId: "1:166105733449:web:f27874792da9c67ccb6298"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const photos = (uuid, count) =>
  Array.from({ length: count }, (_, i) =>
    `https://kolesa-photos.kcdn.online/webp/${uuid.slice(0,2)}/${uuid}/${i + 1}-750x470.webp`
  );

const listings = [
  {
    id: 'merc-e240-2005',
    source: 'internal',
    sourceUrl: 'https://kolesa.kz/a/show/215677355',
    title: 'Mercedes-Benz E 240',
    brand: 'Mercedes-Benz',
    model: 'E 240',
    year: 2005,
    priceKzt: 5600000,
    monthlyPaymentKzt: 115000,
    downPaymentKzt: 1120000,
    city: 'Астана',
    region: 'Акмолинская',
    bodyType: 'Седан',
    engineLiters: 2.6,
    fuelType: 'Бензин',
    mileageKm: 300000,
    gearbox: 'Автомат',
    drive: 'Задний',
    steeringWheel: 'left',
    color: 'Белый металлик',
    customsClearedKz: true,
    condition: 'used',
    isHit: false,
    isActive: true,
    photoColor: '#1A1A1A',
    options: ['Легкосплавные диски', 'Кожаный салон', 'Климат-контроль', 'Круиз-контроль'],
    sellerComment: 'Не требует вложений. Растаможен, поставлен на учёт в Казахстане.',
    photos: photos('7ed55067-f1a3-4cc0-bb49-a16e099af2c3', 7),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'kia-rio-2022',
    source: 'internal',
    sourceUrl: 'https://kolesa.kz/a/show/216622294',
    title: 'Kia Rio',
    brand: 'Kia',
    model: 'Rio',
    year: 2022,
    priceKzt: 7100000,
    monthlyPaymentKzt: 146000,
    downPaymentKzt: 1420000,
    city: 'Астана',
    region: 'Акмолинская',
    bodyType: 'Седан',
    engineLiters: 1.6,
    fuelType: 'Бензин',
    mileageKm: 86000,
    gearbox: 'Автомат',
    drive: 'Передний',
    steeringWheel: 'left',
    color: 'Белый металлик',
    customsClearedKz: true,
    condition: 'used',
    isHit: true,
    isActive: true,
    photoColor: '#05141F',
    options: [
      'Легкосплавные диски', 'Хрустальные фары', 'Противотуманные фары',
      'Обогрев зеркал', 'Велюровый салон', 'Круиз-контроль',
      'Навигационная система', 'Обогрев руля', 'Обогрев сидений',
      'Камера заднего вида', 'Климат-контроль',
    ],
    sellerComment: 'Полная комплектация. Один владелец, без ДТП.',
    photos: photos('d1ca3f90-5bcf-4eac-ba27-a1826ff06e23', 7),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hyundai-accent-2011',
    source: 'internal',
    sourceUrl: 'https://kolesa.kz/a/show/216622734',
    title: 'Hyundai Accent',
    brand: 'Hyundai',
    model: 'Accent',
    year: 2011,
    priceKzt: 3800000,
    monthlyPaymentKzt: 78000,
    downPaymentKzt: 760000,
    city: 'Астана',
    region: 'Акмолинская',
    bodyType: 'Седан',
    engineLiters: 1.4,
    fuelType: 'Бензин',
    mileageKm: 230000,
    gearbox: 'Автомат',
    drive: 'Передний',
    steeringWheel: 'left',
    color: 'Серый металлик',
    customsClearedKz: true,
    condition: 'used',
    isHit: false,
    isActive: true,
    photoColor: '#002C5F',
    options: [
      'Легкосплавные диски', 'Хрустальные фары', 'Автозапуск',
      'Обогрев руля', 'Обогрев сидений', 'Камера заднего вида', 'Кондиционер',
    ],
    sellerComment: 'Ухоженный автомобиль. Сигнализация, автозапуск.',
    photos: photos('4ee2c4fb-f3ad-4024-a978-a18271e0f893', 5),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bmw-520-1991',
    source: 'internal',
    sourceUrl: 'https://kolesa.kz/a/show/216623510',
    title: 'BMW 520',
    brand: 'BMW',
    model: '520',
    year: 1991,
    generation: 'E34',
    priceKzt: 4000000,
    monthlyPaymentKzt: 82000,
    downPaymentKzt: 800000,
    city: 'Астана',
    region: 'Акмолинская',
    bodyType: 'Седан',
    engineLiters: 2.0,
    fuelType: 'Бензин',
    mileageKm: 268900,
    gearbox: 'Механика',
    drive: 'Задний',
    steeringWheel: 'left',
    color: 'Чёрный металлик',
    customsClearedKz: true,
    condition: 'used',
    isHit: false,
    isActive: true,
    photoColor: '#0E1628',
    options: ['Классика BMW E34', 'Задний привод', 'Рядная 6-цилиндровая'],
    sellerComment: 'Легендарная BMW E34 (1988-1996). Надёжна и выносливая.',
    photos: photos('0f287766-ff3c-4b32-a91c-a1827545f172', 7),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hyundai-accent-2021',
    source: 'internal',
    sourceUrl: 'https://kolesa.kz/a/show/216625075',
    title: 'Hyundai Accent',
    brand: 'Hyundai',
    model: 'Accent',
    year: 2021,
    priceKzt: 6600000,
    monthlyPaymentKzt: 136000,
    downPaymentKzt: 1320000,
    city: 'Астана',
    region: 'Акмолинская',
    bodyType: 'Седан',
    engineLiters: 1.4,
    fuelType: 'Бензин',
    mileageKm: 108000,
    gearbox: 'Автомат',
    drive: 'Передний',
    steeringWheel: 'left',
    color: 'Белый металлик',
    customsClearedKz: true,
    condition: 'used',
    isHit: true,
    isActive: true,
    photoColor: '#002C5F',
    options: ['Легкосплавные диски', 'Обогрев сидений', 'Климат-контроль', 'Камера заднего вида'],
    sellerComment: 'Состояние отличное. Обслуживался у официального дилера.',
    photos: photos('3c1ad3c5-6925-4635-9153-a1827cb03a63', 8),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'toyota-lc-2005',
    source: 'internal',
    sourceUrl: 'https://kolesa.kz/a/show/216625508',
    title: 'Toyota Land Cruiser',
    brand: 'Toyota',
    model: 'Land Cruiser',
    year: 2005,
    priceKzt: 7500000,
    monthlyPaymentKzt: 154000,
    downPaymentKzt: 1500000,
    city: 'Астана',
    region: 'Акмолинская',
    bodyType: 'Внедорожник',
    engineLiters: 4.2,
    fuelType: 'Дизель',
    mileageKm: 443305,
    gearbox: 'Механика',
    drive: 'Полный',
    steeringWheel: 'left',
    color: 'Бронзовый металлик',
    customsClearedKz: true,
    condition: 'used',
    isHit: false,
    isActive: true,
    photoColor: '#EB0A1E',
    options: ['Полный привод', 'Дизельный мотор 4.2', 'Раздаточная коробка', 'Пневмоподвеска'],
    sellerComment: 'Легендарный внедорожник. Идеален для любого бездорожья.',
    photos: photos('9509b01c-b4d4-4625-a976-a1827eb9ce5a', 7),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mitsubishi-pajero-2007',
    source: 'internal',
    sourceUrl: 'https://kolesa.kz/a/show/216628365',
    title: 'Mitsubishi Pajero',
    brand: 'Mitsubishi',
    model: 'Pajero',
    year: 2007,
    priceKzt: 7600000,
    monthlyPaymentKzt: 156000,
    downPaymentKzt: 1520000,
    city: 'Астана',
    region: 'Акмолинская',
    bodyType: 'Внедорожник',
    engineLiters: 3.0,
    fuelType: 'Бензин',
    mileageKm: 335000,
    gearbox: 'Автомат',
    drive: 'Полный',
    steeringWheel: 'left',
    color: 'Чёрный металлик',
    customsClearedKz: true,
    condition: 'used',
    isHit: false,
    isActive: true,
    photoColor: '#C20021',
    options: [
      'Легкосплавные диски', 'Ксеноновые фары', 'Кожаный салон',
      'Вставки под дерево', 'Круиз-контроль', 'Обогрев сидений',
      'Память сидений', 'Камера заднего вида',
    ],
    sellerComment: 'Полный привод. Богатая комплектация. Ксенон, кожа.',
    photos: photos('321e242e-03cb-4424-b3ef-a1828b494619', 7),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'merc-ml350-2007',
    source: 'internal',
    sourceUrl: 'https://kolesa.kz/a/show/216629188',
    title: 'Mercedes-Benz ML 350',
    brand: 'Mercedes-Benz',
    model: 'ML 350',
    year: 2007,
    priceKzt: 5200000,
    monthlyPaymentKzt: 107000,
    downPaymentKzt: 1040000,
    city: 'Астана',
    region: 'Акмолинская',
    bodyType: 'Внедорожник',
    engineLiters: 3.5,
    fuelType: 'Бензин',
    mileageKm: 457000,
    gearbox: 'Автомат',
    drive: 'Полный',
    steeringWheel: 'left',
    color: 'Серебристый металлик',
    customsClearedKz: true,
    condition: 'used',
    isHit: false,
    isActive: true,
    photoColor: '#1A1A1A',
    options: [
      'Защита картера', 'Климат-контроль', 'Круиз-контроль',
      'Мультируль', 'Камера заднего вида',
    ],
    sellerComment: 'Легкосплавные литые диски, защита картера, климат, круиз, мультируль, камера.',
    photos: photos('5a68a126-3806-4e03-b722-a1828eead621', 7),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'nissan-pathfinder-2015',
    source: 'internal',
    sourceUrl: 'https://kolesa.kz/a/show/216630442',
    title: 'Nissan Pathfinder',
    brand: 'Nissan',
    model: 'Pathfinder',
    year: 2015,
    priceKzt: 10000000,
    monthlyPaymentKzt: 206000,
    downPaymentKzt: 2000000,
    city: 'Астана',
    region: 'Акмолинская',
    bodyType: 'Внедорожник',
    engineLiters: 3.5,
    fuelType: 'Бензин',
    mileageKm: 200000,
    gearbox: 'Вариатор',
    drive: 'Полный',
    steeringWheel: 'left',
    color: 'Чёрный металлик',
    customsClearedKz: true,
    condition: 'used',
    isHit: true,
    isActive: true,
    photoColor: '#C3002F',
    options: [
      'Полный привод', 'Вариатор', 'Просторный салон',
      'Третий ряд сидений', 'Климат-контроль', 'Камера заднего вида',
    ],
    sellerComment: 'Вместительный семейный внедорожник. 7 мест, полный привод.',
    photos: photos('ae6cbbd7-ce0e-4410-a65f-a182948a91ae', 1),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'nissan-teana-2011',
    source: 'internal',
    sourceUrl: 'https://kolesa.kz/a/show/216631046',
    title: 'Nissan Teana',
    brand: 'Nissan',
    model: 'Teana',
    year: 2011,
    priceKzt: 4500000,
    monthlyPaymentKzt: 93000,
    downPaymentKzt: 900000,
    city: 'Астана',
    region: 'Акмолинская',
    bodyType: 'Седан',
    engineLiters: 2.5,
    fuelType: 'Бензин',
    mileageKm: 235000,
    gearbox: 'Вариатор',
    drive: 'Передний',
    steeringWheel: 'left',
    color: 'Серый металлик',
    customsClearedKz: true,
    condition: 'used',
    isHit: false,
    isActive: true,
    photoColor: '#C3002F',
    options: ['Просторный салон', 'Кожаный руль', 'Климат-контроль', 'Камера заднего вида'],
    sellerComment: 'Просторный бизнес-седан. Вариатор в хорошем состоянии.',
    photos: photos('4a9174bc-afcf-4dde-8d03-a1829754185c', 6),
    createdAt: new Date().toISOString(),
  },
];

async function seed() {
  console.log('Seeding Firestore with', listings.length, 'listings...');
  for (const listing of listings) {
    const { id, ...data } = listing;
    await setDoc(doc(collection(db, 'listings'), id), data);
    console.log('✓', listing.title, listing.year);
  }
  console.log('\nDone! All listings uploaded to Firestore.');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});